name: Check flake
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  check-flake:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Check flake
        run: nix flake check
